defaultSeverity: warning
reportDescriptionlessDisables: true
reportInvalidScopeDisables: true
reportNeedlessDisables: true

extends:
  - stylelint-config-standard-scss
  - stylelint-config-idiomatic-order
  - stylelint-config-prettier
# plugins:
# - stylelint-scss
overrides:
  - customSyntax: '@stylelint/postcss-css-in-js'
    files:
      - src/**/*.tsx
  - customSyntax: postcss-scss
    files:
      - src/**/*.scss
rules:
  # at-rule-empty-line-before: 'always'
  at-rule-no-unknown: null
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules: ['tailwind', 'apply', 'responsive', 'variants', 'screen']
  at-rule-no-vendor-prefix: true
  font-family-name-quotes: 'always-where-recommended'
  font-weight-notation: 'named-where-possible'
  function-url-quotes: 'always'
  media-feature-name-no-vendor-prefix: true
  no-descending-specificity: null
  property-no-vendor-prefix: true
  # selector-attribute-quotes: 'always'
  selector-no-vendor-prefix: true
  # string-quotes: 'single'
  # unit-allowed-list: ['em', 'rem', 's']
  value-no-vendor-prefix: true
