extends:
  - stylelint-config-standard
  - stylelint-config-idiomatic-order
plugins:
  - stylelint-scss
  # - stylelint-order
# syntax:
# - scss
# ignoreFiles:
# - 'node_modules/**/*'
# - 'dist/**/*'
# - '**/*.d.ts'
rules:
  at-rule-empty-line-before: 'never'
  at-rule-no-unknown: null
  scss/at-rule-no-unknown:
    - true
    - ignoreAtRules: ['tailwind', 'apply', 'responsive', 'variants', 'screen']
  at-rule-no-vendor-prefix: true
  font-family-name-quotes: 'always-where-recommended'
  font-weight-notation: 'named-where-possible'
  function-url-quotes: 'always'
  media-feature-name-no-vendor-prefix: true
  no-descending-specificity: null
  number-leading-zero: 'never'
  property-no-vendor-prefix: true
  selector-attribute-quotes: 'always'
  selector-no-vendor-prefix: true
  # string-quotes: "double"
  # unit-allowed-list: ['em', 'rem', 's']
  value-no-vendor-prefix: true
  value-list-comma-newline-after: 'never-multi-line'
