defaultSeverity: warning
reportDescriptionlessDisables: true
reportInvalidScopeDisables: true
reportNeedlessDisables: true

extends:
  - stylelint-config-standard
  - stylelint-config-idiomatic-order
  # - stylelint-a11y/recommended  # enable when support for stylelint 14 is merged
  - stylelint-config-prettier
plugins:
  - stylelint-declaration-strict-value
overrides:
  - customSyntax: '@stylelint/postcss-css-in-js'
    files:
      - src/**/*.tsx
  - customSyntax: postcss-scss
    extends:
      - stylelint-config-standard-scss
    files:
      - src/**/*.scss
    rules:
      at-rule-no-unknown: null
      scss/at-rule-no-unknown:
        - true
        - ignoreAtRules:
            ['tailwind', 'apply', 'responsive', 'variants', 'screen']
rules:
  # at-rule-empty-line-before: 'always'
  at-rule-no-unknown:
    - true
    - ignoreAtRules: ['tailwind']
  at-rule-no-vendor-prefix: true
  font-family-name-quotes: 'always-where-recommended'
  font-weight-notation: 'named-where-possible'
  function-url-quotes: 'always'
  media-feature-name-no-vendor-prefix: true
  no-descending-specificity: null
  property-no-vendor-prefix: true
  scale-unlimited/declaration-strict-value:
    - ['/color$/', '/font$/', '/background$/']
    - disableFix: true
  # selector-attribute-quotes: 'always'
  selector-no-vendor-prefix: true
  string-quotes: 'single'
  # unit-allowed-list: ['em', 'rem', 's']
  value-no-vendor-prefix: true

  # enable when support for stylelint 14 is merged
  # a11y/content-property-no-static-value: true
  # a11y/font-size-is-readable: true
  # a11y/line-height-is-vertical-rhythmed: true
  # a11y/media-prefers-color-scheme: true
  # a11y/no-display-none: true
  # a11y/no-obsolete-attribute: true
  # a11y/no-obsolete-element: true
  # a11y/no-spread-text: true
  # a11y/no-text-align-justify: true
