plugins:
  jsx: true
rules:
  terminology:
    # Load default terms (see terms.json in the repository)
    defaultTerms: true
    # Syntax elements to skip. Overrides the default
    # skip:
    #   - Blockquote
    # List of terms
    # terms:
    #   - JavaScript
    #   - ESLint
    #   - Sass
    #   - Less
    #   # RegExp (case-insensitive) → replacement
    #   - - 'front[- ]end(\w*)'
    #     - frontend$1
    #   - - 'back[- ]end(\w*)'
    #     - backend$1
    #   - - 'web[- ]?site(s?)'
    #     - site$1
    #   - - 'hot[- ]key'
    #     - hotkey
    #   - - repo\b
    #     - repository
    #   - - CLI tool(s?)
    #     - command line tool$1
    #   - - build system(s?)
    #     - build tool$1
    #   - - 'id[''’]?s'
    #     - IDs
    #   - - '(\w+[^.?!]\)? )webpack'
    #     - $1webpack
    #   - - '(\w+[^.?!]\)? )internet'
    #     - $internet
    # # OR load terms from a file
    # "terms": "~/terms.json",
    # OR load terms from npm
    # "terms": "@johnsmith/terms",
    # Excludes terms
    # exclude:
    #   - CSS
