[build]
command = "ls -la && printenv && npm run build"
publish = ".next"

# ignore = "git diff --quiet \"${CACHED_COMMIT_REF}\" \"${COMMIT_REF}\" src/**/* public/* netlify.toml next-env.d.ts next-sitemap.js next.config.js package.json pnpm-lock.yaml postcss.config.js tailwind.config.js tsconfig.json"
# ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- src/ public/ netlify.toml next.config.js pnpm-lock.yaml"
[build.environment]
# CI = "1"
# cache Cypress binary in local "node_modules" folder
# so Netlify caches it
# CYPRESS_CACHE_FOLDER = "./node_modules/CypressBinary"
# set TERM variable for terminal output
TERM = "xterm"
# suppress browserslist notice
BROWSERSLIST_IGNORE_OLD_DATA = "true"

# If skip_processing = true, all other settings are ignored
[build.processing]
skip_processing = false

[build.processing.css]
bundle = true
minify = false

[build.processing.js]
bundle = true
minify = false

[build.processing.html]
pretty_urls = true

[build.processing.images]
compress = true

[context.production.environment]
NEXT_SERVERLESS = "true"
NODE_ENV = "production"

[context.server.environment]
NEXT_SERVERLESS = "false"
NODE_ENV = "production"

[[plugins]]
package = "@netlify/plugin-nextjs"

# [[plugins]]
# runs Cypress tests against the deployed URL
# package = "netlify-plugin-cypress"
# [plugins.inputs]
# record = true
# spec = "cypress/integration/smoke/*.js"
# pa11y config
[[plugins]]
package = "netlify-plugin-a11y"

[plugins.inputs]
checkPaths = ['/']
resultMode = "warn" # is "error" by default

# ignoreDirectories = ['/admin']  # explicitly ignore these directories
[[plugins]]
package = "netlify-plugin-html-validate"

[[plugins]]
package = "netlify-plugin-checklinks"

[plugins.inputs]
entryPoints = ["*.html"]
recursive = true
pretty = true
checkExternal = true
followSourceMaps = true
skipPatterns = [
  "fonts.gstatic.com",
  "amphtml",
  "chunks",
  "_next",
  "index.html",
  "legal",
  "dog",
  "fauna-",
  "page-1",
  "first-amp",
  "account-settings"
]
# eslint-disable-next-line toml/array-element-newline
todoPatterns = ["hybrid", ".css"]

# # lighthouse config
# [[plugins]]
# package = "@netlify/plugin-lighthouse"
#   # optional, fails build when a category is below a threshold
#   [plugins.inputs.thresholds]
#   performance = 0.9
#   accessibility = 0.9
#   best-practices = 0.9
#   seo = 0.8
#   [[plugins.inputs.audits]]
#   path = "de/legal"
#   [[plugins.inputs.audits]]
#   path = "first-amp"
#     [plugins.inputs.audits.thresholds]
#     performance = 0.8

# # sentry config (only public repos in free version)
# [[plugins]]
# package = "@sentry/netlify-build-plugin"

# [plugins.inputs]
# sentryOrg = "vehicle-jg"
# sentryProject = "notari"
