defaultSeverity: warning

extends:
  - stylelint-config-standard
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules: ['tailwind']
  at-rule-no-vendor-prefix: true
  font-family-name-quotes: 'always-where-recommended'
  font-weight-notation: 'named-where-possible'
  function-url-quotes: 'always'
  media-feature-name-no-vendor-prefix: true
  no-descending-specificity: null
  property-no-vendor-prefix: true
  scale-unlimited/declaration-strict-value:
    - ['/color$/', '/font$/', '/background$/']
    - disableFix: true
  selector-no-vendor-prefix: true
  string-quotes: 'single'
  value-list-comma-newline-after: 'always-multi-line'
  value-no-vendor-prefix: true
