# https://github.com/thomaseizinger/create-pull-request
name: 'Create PR'

on:
  create:
    branches:
      - '**'

jobs:
  create-pr-for-branch:
    if: |
      contains(github.ref, 'einSelbst') == false &&
      contains(github.ref, 'dependabot') == false &&
      contains(github.ref, 'renovate') == false
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: JasonEtco/smee-action@v2
        with:
          channel: grW1TqGJMKSq2S

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Print environment variables
        run: |
          echo "CI_REPOSITORY_SLUG=$CI_REPOSITORY_SLUG"
          echo "CI_REPOSITORY_OWNER=$CI_REPOSITORY_OWNER"
          echo "CI_REPOSITORY_OWNER_SLUG=$CI_REPOSITORY_OWNER_SLUG"
          echo "CI_REPOSITORY_NAME=$CI_REPOSITORY_NAME"
          echo "CI_REPOSITORY_NAME_SLUG=$CI_REPOSITORY_NAME_SLUG"
          echo "CI_REPOSITORY=$CI_REPOSITORY"
          echo "CI_REF_SLUG=$CI_REF_SLUG"
          echo "CI_ACTION_REF_NAME=$CI_ACTION_REF_NAME"
          echo "CI_ACTION_REF_NAME_SLUG=$CI_ACTION_REF_NAME_SLUG"
          echo "CI_REF_NAME=$CI_REF_NAME"
          echo "CI_REF_NAME_SLUG=$CI_REF_NAME_SLUG"
          echo "CI_REF=$CI_REF"
          echo "CI_SHA_SHORT=$CI_SHA_SHORT"
          echo "CI_SHA=$CI_SHA"
          echo "CI_ACTOR=$CI_ACTOR"
          echo "CI_EVENT_NAME=$CI_EVENT_NAME"
          echo "CI_RUN_ID=$CI_RUN_ID"
          echo "CI_RUN_NUMBER=$CI_RUN_NUMBER"
          echo "CI_WORKFLOW=$CI_WORKFLOW"
          echo "CI_ACTION=$CI_ACTION"

      - name: Create pull request to main
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          draft: true
          title: ${{ steps.extract_branch.outputs.branch }}
          body: |
            Hi!
            This PR was created in response to a new branch pushed from ${github.actor}.
            I will to the following things for you:
              - deploy to vercel
              - deploy to netlify
              - run lighthouse check on vercel and add the results
              - ...wip

      # GitHub Action does not allow recursion so the CI checks are
      # not triggered when the branch is pushed
      - name: Trigger CI checks for new pull request
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          event-type: new-pull-request
          client-payload: |
            {
            "branch-name": "${{steps.extract_branch.outputs.branch }}"}
            "ref": "${{ github.ref }}",
            "sha": "${{ github.sha }}"
            }
