# https://github.com/thomaseizinger/create-pull-request
name: 'Create PR'

on:
  create:
    branches:
      - '**'

jobs:
  create-pr-for-branch:
    if: |
      startsWith(github.ref, 'einSelbst') == false &&
      startsWith(github.ref, 'dependabot') == false &&
      startsWith(github.ref, 'renovate') == false
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

      - name: Create pull request to main
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          base: main
          title: ${{ steps.extract_branch.outputs.branch }}
          body: |
            Hi!
            This PR was created in response to a new branch.

      - name: Create pull request to pure
        uses: thomaseizinger/create-pull-request@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: ${{ github.ref }}
          # head: release/v${{ github.event.inputs.versionName }}
          base: pure
          title: ${{ steps.extract_branch.outputs.branch }}
          body: |
            Hi!
            This PR was created in response to a new branch.
            $GITHUB_WORKFLOW - The name of the workflow
            $GITHUB_RUN_ID	A unique number for each run within a repository. This number does not change if you re-run the workflow run.
            $GITHUB_RUN_NUMBER	A unique number for each run of a particular workflow in a repository. This number begins at 1 for the workflow's first run, and increments with each new run. This number does not change if you re-run the workflow run.
            $GITHUB_ACTION	The unique identifier (id) of the action.
            $GITHUB_ACTIONS	Always set to true when GitHub Actions is running the workflow. You can use this variable to differentiate when tests are being run locally or by GitHub Actions.
            %GITHUB_ACTOR	The name of the person or app that initiated the workflow. For example, octocat.
            $GITHUB_REPOSITORY	The owner and repository name. For example, octocat/Hello-World.
            $GITHUB_EVENT_NAME	The name of the webhook event that triggered the workflow.
            $GITHUB_EVENT_PATH	The path of the file with the complete webhook event payload. For example, /github/workflow/event.json.
            $GITHUB_WORKSPACE	The GitHub workspace directory path. The workspace directory is a copy of your repository if your workflow uses the actions/checkout action. If you don't use the actions/checkout action, the directory will be empty. For example, /home/runner/work/my-repo-name/my-repo-name.
            $GITHUB_SHA	The commit SHA that triggered the workflow. For example, ffac537e6cbbf934b08745a378932722df287a53.
            $GITHUB_REF	The branch or tag ref that triggered the workflow. For example, refs/heads/feature-branch-1. If neither a branch or tag is available for the event type, the variable will not exist.
            $GITHUB_HEAD_REF	Only set for pull request events. The name of the head branch.
            $GITHUB_BASE_REF	Only set for pull request events. The name of the base branch.
            $GITHUB_SERVER_URL	Returns the URL of the GitHub server. For example: https://github.com.
            $GITHUB_API_URL	Returns the API URL. For example: https://api.github.com.
            $GITHUB_GRAPHQL_URL GraphQL URL
