name: Continuous integration

on:
  pull_request:
    branches:
      - main
      - pure
  repository_dispatch:
    types:
      - ci-checks

jobs:
  ci:
    name: Validate
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install pnpm
        run: |
          npm install pnpm@next -g
          pnpm --version

      - name: pnpm install
        run: pnpm install

      - name: Cache pnpm directory
        id: cache-pnpm-dir
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Install dependencies
        if: steps.cache-pnpm-dir.outputs.cache-hit != 'true'
        run: pnpm install --prefer-frozen-lockfile

      - name: Run prettier
        run: pnpm format

      - name: Run eslint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build
        run: pnpm build
