name: Debug
on:
  pull_request:
  push:
  repository_dispatch:

jobs:
  debug-action:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        uses: hmarr/debug-action@master

      - uses: JasonEtco/smee-action@v2
        with:
          channel: grW1TqGJMKSq2S
