name: Debug
on:
  pull_request:
  push:
  repository_dispatch:

jobs:
  debug-action:
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        uses: hmarr/debug-action@master

      - uses: JasonEtco/smee-action@v2
        with:
          channel: grW1TqGJMKSq2S

  Find-PR:
    name: PR finder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Find the PR associated with this push, if there is one.
      - uses: jwalton/gh-find-current-pr@v1
        id: findPr

      # This will echo "Your PR is 7", or be skipped if there is no current PR.
      - run: echo "Your PR is ${PR}"
        if: success() && steps.findPr.outputs.number
        env:
          PR: ${{ steps.findPr.outputs.pr }}
