# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#configuring-workflow-events
name: Audit

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  repository_dispatch:
    types:
      - ci-checks

jobs:
  Compressed Size:
    name: Compare compressed file sizes
    runs-on: ubuntu-latest

    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2-beta
        with:
          fetch-depth: 1
      - name: Check and report changes in the application's package size
        uses: preactjs/compressed-size-action@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          build-script: 'build:ssr'
          # Any JS files anywhere within a dist directory:
          # pattern: ".next/static/**/*.js"
          pattern: '.next/**/*.{css,js,json,html}'
          # pattern: "{build/**/*.js,build/**/*.css}" # multiple paths
          # compression: none
          # show-total: false
          # compression: brotli
          # Always ignore SourceMaps and node_modules:
          # exclude: "{**/*.map,**/cache/**}"
          exclude: '**/cache/**'
          strip-hash: "[\\/\\.-]([\\w-]{20,21})[\\.\\/]"
          # Ignore changes of less than 100 bytes
          minimum-change-threshold: 100
