name: Create Card

on:
  pull_request_target:
    types: [synchronize, ready_for_review]

jobs:
  createCard:
    name: Create Card for PR
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        id: card-creation
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Main Project
          column-name: In progress
          issue-number: ${{ github.event.number }}

      - name: Check output
        run: echo ${{ steps.card-creation.outputs.card-id }}
