on:
  pull_request_target:
    types: [opened]
  issue_comment:
    types: [edited]
  workflow_run:
    workflows: ['Create PR']
    types: [completed]

jobs:
  createCard:
    name: Create Card for PR
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Create or Update Project Card
        id: card-creation
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Main Project
          column-name: In progress
          issue-number: ${{ github.event.number }}

      - name: Check output
        run: echo ${{ steps.card-creation.outputs.card-id }}
