name: Scan Code for Secrets

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect Secrets
        uses: CorrelatedLabs/detect-secrets-action@0.2.0
      # https://github.com/safernandez666/DevOps/blob/dcfcb8120ec57e60e03b079457cfd5668e60646c/.github/workflows/push.yml
      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
        with:
          DS_REQUIRE_BASELINE: true

      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build(detect-secrets): Commit the newly-generated .secrets.baseline file'
          branch: main
          file_pattern: .secrets.baseline

      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          output: reports
          # type: "credscan,python,nodejs,csharp,terraform,yaml,bash,depscan"
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports

      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
