name: Security Audits

on:
  push:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  check-for-secrets:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # this does not really work
      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0

      - name: Commit back .secrets.baseline (if it was missing)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'build(detect-secrets): Commit the newly-generated .secrets.baseline file'
          branch: main
          file_pattern: .secrets.baseline

      - name: remove pnpm lock file
        run: 'rm ./pnpm-lock.yaml'

      # this seems to work but gets false positives
      - name: Perform Scan
        uses: ShiftLeftSecurity/scan-action@master
        with:
          output: reports
          # type: "credscan,python,nodejs,csharp,terraform,yaml,bash,depscan"
        env:
          WORKSPACE: https://github.com/${{ github.repository }}/blob/${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SCAN_ID: ${{ github.run_id }}

      - name: Upload sarif scan report
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: reports

      - name: Upload scan reports again
        uses: actions/upload-artifact@v2
        with:
          name: shiftleft-scan-reports
          path: reports

      # this seems to work but gets false positives
      # also this has master branch hardcoded in the action, maybe an issue
      - name: Detect Secrets
        uses: CorrelatedLabs/detect-secrets-action@0.2.0
