name: Lint Code Base

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Cache some stuff
        id: cache-pnpm-dir
        uses: actions/cache@main
        env:
          cache-name: cache-pnpm-store
        with:
          path: |
            ~/.pnpm-store
            ${{ github.workspace }}/node_modules
            ${{ github.workspace }}/.next/cache
            ~/.cache/Cypress
          key: |
            ${{ runner.os }}-${{ node-version }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ node-version }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-${{ node-version }}-build-

      - name: Install pnpm
        uses: pnpm/action-setup@master
        with:
          version: next

      - name: Install dependencies
        if: steps.cache-pnpm-dir.outputs.cache-hit != 'true'
        run: |
          pnpm --version
          pnpm install --prefer-frozen-lockfile

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          JAVASCRIPT_DEFAULT_STYLE: prettier
          TYPESCRIPT_DEFAULT_STYLE: prettier
          CSS_FILE_NAME: .stylelintrc.yml
          NATURAL_LANGUAGE_CONFIG_FILE: .textlintrc.yml
          YAML_CONFIG_FILE: .yamllint

          # is default anyway
          # JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          # TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.yml
          # VALIDATE_JAVASCRIPT_ES: true
          # VALIDATE_CSS: true

          # disable standard js linter to allow trailing commas
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
