name: Auto-update CSS at projectwallace.com

on:
  push:

jobs:
  analyze-css:
    name: CSS Analyzer
    if: false # skip for now, not working
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          ls -la
          cd .next
          ls -la

      - name: Project Wallace Diff
        # uses: einSelbst/css-diff-action@einSelbst-import-path
        uses: projectwallace/push-css-action@master
        with:
          project-wallace-token: ${{ secrets.PROJECT_WALLACE_TOKEN }}
          css-path: .next/static/css/
          post-pr-comment: true
